version: '3'

services:
  redis:
    image: 'redis:6.2.10-alpine3.17'
    container_name: redis-label
    volumes:
      - /apps/redis/datadir:/data
      - /apps/redis/conf/redis.conf
#      - /apps/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /apps/redis/logs:/logs
    command: redis-server --requirepass 111111
    ports:

      - 6379:6379
  mysql:
    image: 'mysql:latest'
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - 9910:3306
    environment:
      - MYSQL_DATABASE=tiktok
      - MYSQL_USER=tiktok
      - MYSQL_PASSWORD=tiktok
      - MYSQL_ROOT_PASSWORD=111111
#      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  Etcd:
    image: "quay.io/coreos/etcd:v3.5.5"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3
    ports:
      - 2379:2379
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
